### ISSUE TITLE
Fill with mock doesn't work ?

### ISSUE THREAD

**Issue by paudebert** [Abc-Arbitrage/Abc.MoqComplete#16] opened 2020-12-01 12:51 UTC
Hello,
Since the last version the 'fill with mock' functionality doesn't work. I only have 'Fill current parameter with mock'
This is regratable when I have multiple dependency injection.

My setup is 
Resharper 2020.2.4
VS 2019 (16.7.6)
Xunit

![image](https://user-images.githubusercontent.com/75314535/100745168-2b2c9e00-33df-11eb-9eaf-2efcff7443f1.png)

**Comment by paudebert** [comment] 2020-12-01 13:25
My bad in a tiny project it's working 
![image](https://user-images.githubusercontent.com/75314535/100746342-ddb13080-33e0-11eb-8e34-ffa77082feba.png)

What can I do in a bigger one ?

**Comment by lconstan** [comment] 2020-12-02 18:51
Can you please share a solution with the issue, so that I can investigate?
Or, give your classes/interface signature to try a reproduction of the bug.

**Comment by lconstan** [comment] 2020-12-09 19:46
@paudebert any news on the above?
You might have this behavior because your constructor have parameters that are not interface nor abstract classes

**Comment by lconstan** [comment] 2021-01-09 09:39
Closing this as no answer. Please reopen if needed

**Closed as completed by lconstan** 2021-01-09 09:39 UTC
